# Generated by Django 5.0.4 on 2024-05-05 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgreapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='fkuser',
            field=models.ManyToManyField(related_name='userproperty', to=settings.AUTH_USER_MODEL),
        ),
    ]
