# Generated by Django 5.0.4 on 2024-05-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgreapi', '0003_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
